#!/bin/sh

for row in 0 1
do
  for b in $(seq 0 7)
  do
    b=$((b+row*8))
    f=$(((1-b/8)*15))
    printf '\33[48;5;%dm\33[38;5;%dm%9d\33[0m' $b $f $b
  done
  echo
done

for row in 0 1
do
  for y in $(seq 0 5)
  do
    for x in $(seq 0 17)
    do
      x=$((x+row*18))
      i=$((y*36+x))
      b=$((16+i))
      f=$(((1-x/18)*15))
      printf '\33[48;5;%dm\33[38;5;%dm%4d\33[0m' $b $f $b
    done
    echo
  done
done

for row in 0 1
do
  for i in $(seq 0 11)
  do
    i=$((i+row*12))
    b=$((232+i))
    f=$(((1-i/12)*15))
    printf '\33[48;5;%dm\33[38;5;%dm%6d\33[0m' $b $f $b
  done
  echo
done
